### ISSUE TITLE
nice mod

### ISSUE THREAD

**Issue by Belinhagamer999** [Maximilian2022/AmongUs-Mod-Auto-Deploy-Script#2]
but how does it works? I don't understand japanese
I'm just among us hacker

**Comment by Maximilian2022** [comment]
This script is just a deployment script. not a MOD itself.

Run bat file w/ your own risk.

from the latest updates, if OS language is not Japanese, almost all message will be google-translated to your OS language.
i dont care display area so you may face reading problem though.

https://github.com/Maximilian2022/AmongUs-Mod-Auto-Deploy-Script/releases/download/latest/StartAmongUsModTORplusDeployScript.bat

when you run bat, it downloads latest ps1 file and run it.

ps1 file will check ps v7 is in there or not, and install ps v7 without ask if not installed.
if ps1 file install ps v7, then you need to re-run bat file.

after you re-run batfile, you may see GUI.
if you are using security apps (e.g. Kaspelsky), script wont run. security apps may block.
if you are installing original amongus folder w/ custom place, then you need to specify where is original amongus installed folder.

after that, plz read following. you may need google translate.
https://github.com/Maximilian2022/AmongUs-Mod-Auto-Deploy-Script/wiki/%E3%81%93%E3%81%AEScript%E3%81%A7%E3%82%84%E3%81%A3%E3%81%A6%E3%82%8B%E3%81%93%E3%81%A8
https://github.com/Maximilian2022/AmongUs-Mod-Auto-Deploy-Script/wiki
